# Generated by Django 4.2 on 2023-04-11 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 13, 54, 51, 928342, tzinfo=datetime.timezone.utc)),
        ),
    ]
