# Generated by Django 4.2 on 2023-04-12 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 7, 0, 4, 390045, tzinfo=datetime.timezone.utc)),
        ),
    ]
